### ISSUE TITLE
Feature request: render user-defined commands

### ISSUE THREAD

**Issue by hljeong** [yfzhao20/vscode-ultra-math-preview#1]
It would be nice if user-defined commands could be rendered like LaTeX-Workshop does: 

![image](https://user-images.githubusercontent.com/73093197/155238782-c8ac4f72-333b-4ddf-9057-19716e0aef11.png)

**Comment by yfzhao20** [comment]
Thanks for your feedback! I will fix that in next version.

**Comment by yfzhao20** [comment]
Should be fixed in 0.1.1 version. Have a try! 😉

**Comment by hljeong** [comment]
The demo looks great!
But the extension actually stops working for me altogether...
Version 0.1.0 works fine but the preview does not show up at all in versions 0.1.1 and 0.1.2.
I also tried disabling all other extensions but the preview still doesn't show up.

0.1.0: 
![image](https://user-images.githubusercontent.com/73093197/156084136-27a5864f-b60d-4af0-959a-a3ef619020bf.png)

0.1.1: 
![image](https://user-images.githubusercontent.com/73093197/156084167-30886941-3b7b-4640-adab-d6a609c55ce4.png)

0.1.2: 
![image](https://user-images.githubusercontent.com/73093197/156084197-63cd5861-11aa-46ec-8633-7c7f1d96f2c9.png)

**Comment by yfzhao20** [comment]
Thanks for your feedback! However it looks fine in my PC. Try these steps to find the problem:
1. reload the window and open an `.md` or `.tex` file to test;
2. `ctrl+shift+p` and execute the command `Developer: Toggle Developer Tools`. Then do this:

![image](https://user-images.githubusercontent.com/80528249/156092466-59220c76-cb0e-4ba3-8d45-81e12e9a5a4e.png)

3. right-click on your formula and execute "ultra math preview: reload preview"
4. `ctrl+shift+p` and execute the command `Open Settings (JSON)` . then copy `"umath.preview.enableMathPreview": true` to your `settings.json` file.

If there is any problem, please keep me known. Thanks!

**Comment by hljeong** [comment]
I found out that `\newcommand*` breaks the preview: 

![image](https://user-images.githubusercontent.com/73093197/156453391-fd5d6339-869f-4d6c-ab1a-e1a28756e019.png)

Having an argument makes it disappear completely: 

![image](https://user-images.githubusercontent.com/73093197/156454096-1520358d-e35c-41e2-b388-efdae0d79686.png)



It turns out that my template contained a `\newcommand*` with arguments so the preview were not showing up. Changing the `\newcommand*` to `\newcommand` fixes the problem and doesn't affect my use of the template so the issue should be fixed for me. However this might pose a problem to someone else.

**Comment by yfzhao20** [comment]
Should be fixed in 0.1.4 version. I forcibly let `\newcommand*` be `\newcommand` . Because `\newcommand*` may be unsupported in MathJax. Have a try!😃

By the way, if you use `[1]` in `\newcommand` or `\newcommand*` command, you may put a parameter after you command. 
For example, if you define `newcommand{R}[1]{\mathbb{R}}`, you should throw something after `\R` , like `\R{a}` or just `\R{}`. The lack of parameter may cause error, and then preview panel will disappear.

**Comment by hljeong** [comment]
Thanks!

About the parameter thing: that was a mistake in my screenshot; I meant to show that it did not work even with correct usage, but it seems like it's all fixed now.
